# Generated by Django 5.2.8 on 2025-11-27 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_financeira', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='categoria',
            field=models.CharField(choices=[('salario', 'Salário'), ('alimentacao', 'Alimentação'), ('transporte', 'Transporte'), ('moradia', 'Moradia'), ('lazer', 'Lazer'), ('outros', 'Outros'), ('investimento', 'Investimento')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='tipo',
            field=models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa'), ('investimento', 'Investimento')], max_length=12),
        ),
    ]
